pub struct UiText {
    pub data_generation_heading: &'static str,
    pub price_horizon_heading: &'static str,
    pub time_horizon_heading: &'static str,
    pub pair_selector_heading: &'static str,
    pub view_options_heading: &'static str,
    pub view_data_source_heading: &'static str,
    pub signals_heading: &'static str,
    pub price_horizon_helper_prefix: &'static str,
    pub price_horizon_helper_suffix: &'static str,
    pub time_horizon_helper_prefix: &'static str,
    pub time_horizon_helper_suffix: &'static str,
    pub journey_status_heading: &'static str,
    pub journey_status_waiting: &'static str,
    pub journey_status_no_data: &'static str,
    pub journey_status_no_zones: &'static str,
    pub journey_status_no_executions: &'static str,
    pub journey_status_failed: &'static str,
    pub journey_status_error_prefix: &'static str,
    pub journey_status_current_prefix: &'static str,
    pub journey_status_aggregate_prefix: &'static str,
    pub journey_status_pairs_label: &'static str,
    pub journey_status_zones_label: &'static str,
    pub journey_status_attempts_label: &'static str,
    pub journey_status_success_label: &'static str,
    pub journey_status_timeout_label: &'static str,
    pub journey_status_stopped_label: &'static str,
    pub journey_status_success_rate_label: &'static str,
    pub journey_status_elapsed_label: &'static str,
    pub journey_status_last_run_label: &'static str,
    pub journey_status_ago_suffix: &'static str,
    pub journey_zone_line_prefix: &'static str,
    pub journey_zone_label_attempts_short: &'static str,
    pub journey_zone_label_successes_short: &'static str,
    pub journey_zone_label_timeouts_short: &'static str,
    pub journey_zone_label_stops_short: &'static str,
    pub journey_zone_label_success_rate_short: &'static str,
    pub journey_zone_label_ev_annual_short: &'static str,
    pub journey_zone_label_kelly_short: &'static str,
    pub journey_zone_label_worst_loss_short: &'static str,
    pub journey_zone_label_avg_drawdown_short: &'static str,
    pub plot_x_axis: &'static str,
    pub plot_y_axis: &'static str,
    pub plot_strongest_zone: &'static str,
    pub plot_this_zone_is: &'static str,

    pub label_volume: &'static str,
    pub label_reversal_support: &'static str,
    pub label_reversal_resistance: &'static str,
    pub label_lower_wick_count: &'static str,
    pub label_upper_wick_count:&'static str,
    pub label_hvz: &'static str,
    pub label_lower_wick_zones: &'static str,
    pub label_upper_wick_zones: &'static str,
    pub label_hvz_above: &'static str,
    pub label_hvz_beneath: &'static str,
    pub label_hvz_within: &'static str,
    pub label_help_background: &'static str,
    pub label_help_sim_toggle_direction: &'static str,
    pub label_help_sim_step_size: &'static str,
    pub label_help_sim_activate_price_change: &'static str,
    pub label_help_sim_jump_hvz: &'static str,
    pub label_help_sim_jump_lower_wicks: &'static str,
    pub label_help_sim_jump_higher_wicks: &'static str,

}

pub const UI_TEXT: UiText = UiText {
    data_generation_heading: "Shape Your Trades",
    price_horizon_heading: "Price Horizon",
    time_horizon_heading: "Time Horizon",
    pair_selector_heading: "Select Plot Pair",
    view_options_heading: "View Options",
    view_data_source_heading: "Data Source",
    signals_heading: "🎯 Signals",
    price_horizon_helper_prefix: "Focus on price action within ±",
    price_horizon_helper_suffix: "% of current price",
    time_horizon_helper_prefix: "Focus on trades that complete within ",
    time_horizon_helper_suffix: " days",
    journey_status_heading: "🎯 Journey Outcomes",
    journey_status_waiting: "Waiting for journey results…",
    journey_status_no_data: "No journey data",
    journey_status_no_zones: "No sticky zones",
    journey_status_no_executions: "No journeys completed",
    journey_status_failed: "Journey run failed",
    journey_status_error_prefix: "Error",
    journey_status_current_prefix: "Current pair",
    journey_status_aggregate_prefix: "Across pairs",
    journey_status_pairs_label: "pairs",
    journey_status_zones_label: "key-zones",
    journey_status_attempts_label: "attempts",
    journey_status_success_label: "successes",
    journey_status_timeout_label: "timeouts",
    journey_status_stopped_label: "stops",
    journey_status_success_rate_label: "success rate",
    journey_status_elapsed_label: "elapsed",
    journey_status_last_run_label: "last run",
    journey_status_ago_suffix: "ago",
    journey_zone_line_prefix: "[Journey]",
    journey_zone_label_attempts_short: "attempts",
    journey_zone_label_successes_short: "successes",
    journey_zone_label_timeouts_short: "timeouts",
    journey_zone_label_stops_short: "stops",
    journey_zone_label_success_rate_short: "SR",
    journey_zone_label_ev_annual_short: "EVA",
    journey_zone_label_kelly_short: "Kelly",
    journey_zone_label_worst_loss_short: "worst loss",
    journey_zone_label_avg_drawdown_short: "avg drawdown",
    plot_y_axis: "Price",
    plot_x_axis: "Key Zone Strength (0 % of the strongest zone)",
    plot_strongest_zone: "of strongest zone",
    plot_this_zone_is: "This zone is",
    
    label_volume: "Trading Volume",
    label_lower_wick_count: "Lower Wick Count",
    label_upper_wick_count: "Higher Wick Count",
    label_hvz: "High Volume Zones",
    label_lower_wick_zones: "Lower Wick Zones",
    label_upper_wick_zones: "Upper Wick Zones",
    label_reversal_support: "`High Lower Wick Count Zone` (HLWCZ)  (reversal likely) ",
    label_reversal_resistance: "`High Upper Wick Count Zone` (HUWCZ)  (reversal likely)",
    label_hvz_above: "`High Volume Zone` (HVZ) is above (if bullish, acts as future target price)",
    label_hvz_beneath: "`High Volume Zone` (HVZ) is below (if bearish, acts as future target price)",
    label_hvz_within: "Inside `High Volume Zone` (HVZ) now (consolidation likely)",

    label_help_background: "Rotate Background Data Selection (between (1) Trading Volume, (2) Lower Wick Count ,(3) Upper Wick Count",
    label_help_sim_toggle_direction: "Toggle direction (⬆️ UP / ⬇️ DOWN)",
    label_help_sim_step_size: "Cycle step size (0.1% → 1% → 5% → 10%)",
    label_help_sim_activate_price_change:"Activate price change in current direction",
    label_help_sim_jump_hvz: "Jump to next high volume zone (HVZ)",
    label_help_sim_jump_lower_wicks: "Jump to next high lower wick count zone (HLWCZ)",
    label_help_sim_jump_higher_wicks: "Jump to next high upper wick count zone (HUWCZ)",

};
