//! Configuration module for the klines application.

pub mod analysis;
pub mod binance;
pub mod constants;
pub mod debug;
pub mod demo;
pub mod persistence;
pub mod plot;

// Re-export commonly used items
pub use analysis::{
    CVA_MIN_SECONDS_BETWEEN_RECALCS, CVA_PRICE_RECALC_THRESHOLD_PCT, DEFAULT_PRICE_ZONE_COUNT,
    INTERVAL_WIDTH_TO_ANALYSE_MS, JOURNEY_PRICE_UPDATE_THRESHOLD_PCT,
    JOURNEY_START_PRICE_TOLERANCE_PCT, JOURNEY_STOP_LOSS_PCT, MIN_CANDLES_FOR_ANALYSIS,
    TIME_HORIZON_DEFAULT_DAYS, TIME_HORIZON_MAX_DAYS, TIME_HORIZON_MIN_DAYS,
};
pub use binance::{
    BINANCE_WS_BASE, BINANCE_WS_COMBINED_BASE, BinanceApiConfig, INITIAL_RECONNECT_DELAY_SECS,
    KLINE_ACCEPTABLE_AGE_SECONDS, KLINE_CALL_WEIGHT, MAX_BN_KLINES_LOOKUPS_TOTAL,
    MAX_RECONNECT_DELAY_SECS, SIMULTANEOUS_KLINE_CALLS_CEILING, WEIGHT_LIMIT_MINUTE,
};
pub use constants::{DEFAULT_KLINES_LIMIT, MAX_PAIRS};
pub use debug::{
    PRINT_DECAY_CALIBRATION, PRINT_JOURNEY_SUMMARY, PRINT_ZONE_SCORING_FOR_PAIR,
    PRINT_ZONE_TRANSITION_SUMMARY,
};
pub use demo::{
    WASM_DEMO_CACHE_FILE, WASM_DEMO_PAIRS, WASM_DISABLE_NETWORKING, WASM_KLINE_BUNDLE_DIR,
    WASM_MAX_PAIRS,
};
pub use persistence::{
    APP_STATE_PATH, KLINE_FILENAME_WITHOUT_EXT, KLINE_PATH, KLINE_VERSION, kline_cache_filename,
};
